package com.healthtrack.service;

import com.healthtrack.entity.Habit;
import com.healthtrack.entity.HabitLog;
import com.healthtrack.repository.HabitLogRepository;
import com.healthtrack.repository.HabitRepository;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
public class ExportService {

    @Autowired private HabitRepository habitRepository;
    @Autowired private HabitLogRepository habitLogRepository;

    public byte[] exportHabitsPdf(Long userId, String userName) throws Exception {
        LocalDate endDate = LocalDate.now();
        LocalDate startDate = endDate.minusDays(29); // last 30 days

        List<Habit> habits = habitRepository.findByUserId(userId);
        List<HabitLog> logs = habitLogRepository.findByUserIdAndDateRange(userId, startDate, endDate);

        Document document = new Document(PageSize.A4, 36, 36, 54, 36);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        PdfWriter.getInstance(document, out);
        document.open();

        // Fonts
        Font titleFont   = new Font(Font.FontFamily.HELVETICA, 22, Font.BOLD, new BaseColor(34, 197, 94));
        Font headingFont = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD, new BaseColor(30, 41, 59));
        Font bodyFont    = new Font(Font.FontFamily.HELVETICA, 10, Font.NORMAL, new BaseColor(71, 85, 105));
        Font tableHeader = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, BaseColor.WHITE);
        Font bold        = new Font(Font.FontFamily.HELVETICA, 10, Font.BOLD, new BaseColor(30, 41, 59));

        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("MMM d, yyyy");

        // Title
        Paragraph title = new Paragraph("HealthTrack – Habit Report", titleFont);
        title.setAlignment(Element.ALIGN_CENTER);
        document.add(title);

        Paragraph sub = new Paragraph(userName + "  |  " + startDate.format(fmt) + " – " + endDate.format(fmt), bodyFont);
        sub.setAlignment(Element.ALIGN_CENTER);
        sub.setSpacingAfter(16);
        document.add(sub);

        // Summary box
        long totalPossible  = (long) habits.size() * 30;
        long totalCompleted = logs.stream().filter(l -> Boolean.TRUE.equals(l.getCompleted())).count();
        int  rate           = totalPossible > 0 ? (int) (totalCompleted * 100 / totalPossible) : 0;

        PdfPTable summary = new PdfPTable(3);
        summary.setWidthPercentage(100);
        summary.setSpacingAfter(20);
        addSummaryCell(summary, "Total Habits",    String.valueOf(habits.size()), headingFont, bodyFont);
        addSummaryCell(summary, "Check-ins Done",  totalCompleted + "/" + totalPossible, headingFont, bodyFont);
        addSummaryCell(summary, "Completion Rate", rate + "%", headingFont, bodyFont);
        document.add(summary);

        // Per-habit breakdown
        Paragraph breakdownTitle = new Paragraph("Habit Breakdown (Last 30 Days)", headingFont);
        breakdownTitle.setSpacingAfter(8);
        document.add(breakdownTitle);

        PdfPTable table = new PdfPTable(4);
        table.setWidthPercentage(100);
        table.setWidths(new float[]{3f, 2f, 1.5f, 1.5f});

        // Header row
        BaseColor headerBg = new BaseColor(34, 197, 94);
        for (String h : new String[]{"Habit Name", "Category", "Days Done", "Rate"}) {
            PdfPCell cell = new PdfPCell(new Phrase(h, tableHeader));
            cell.setBackgroundColor(headerBg);
            cell.setPadding(8);
            cell.setBorder(Rectangle.NO_BORDER);
            table.addCell(cell);
        }

        // Data rows
        boolean alt = false;
        BaseColor altBg = new BaseColor(240, 253, 244);
        for (Habit habit : habits) {
            long done = logs.stream()
                    .filter(l -> l.getHabit().getId().equals(habit.getId()) && Boolean.TRUE.equals(l.getCompleted()))
                    .count();
            int habitRate = (int) (done * 100 / 30);
            BaseColor rowBg = alt ? altBg : BaseColor.WHITE;

            addTableCell(table, habit.getName(),         bold,     rowBg);
            addTableCell(table, habit.getCategory(),     bodyFont, rowBg);
            addTableCell(table, done + "/30",            bodyFont, rowBg);
            addTableCell(table, habitRate + "%",         bold,     rowBg);
            alt = !alt;
        }
        document.add(table);

        // Footer
        Paragraph footer = new Paragraph("\nGenerated by HealthTrack on " + endDate.format(fmt), bodyFont);
        footer.setAlignment(Element.ALIGN_RIGHT);
        footer.setSpacingBefore(20);
        document.add(footer);

        document.close();
        return out.toByteArray();
    }

    private void addSummaryCell(PdfPTable t, String label, String value, Font headingFont, Font bodyFont) {
        PdfPCell cell = new PdfPCell();
        cell.setPadding(12);
        cell.setBorderColor(new BaseColor(229, 231, 235));
        cell.setBackgroundColor(new BaseColor(240, 253, 244));
        Paragraph p = new Paragraph();
        p.add(new Chunk(value + "\n", headingFont));
        p.add(new Chunk(label, bodyFont));
        cell.addElement(p);
        t.addCell(cell);
    }

    private void addTableCell(PdfPTable t, String text, Font font, BaseColor bg) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setPadding(7);
        cell.setBorderColor(new BaseColor(229, 231, 235));
        cell.setBackgroundColor(bg);
        t.addCell(cell);
    }
}
